# Generated by Django 4.2.5 on 2023-10-06 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AppFinal", "0003_rename_nombre_trabajos_entregar_trabajo_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tipo_servicio",
            name="telefono",
            field=models.CharField(default=1, max_length=40),
            preserve_default=False,
        ),
    ]
