# Generated by Django 4.2.5 on 2023-10-06 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AppFinal", "0004_tipo_servicio_telefono"),
    ]

    operations = [
        migrations.AddField(
            model_name="tipo_servicio",
            name="acepta",
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
