# Generated by Django 4.2.5 on 2023-10-07 03:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("AppFinal", "0005_tipo_servicio_acepta"),
    ]

    operations = [
        migrations.RemoveField(model_name="tipo_servicio", name="acepta",),
    ]
